[pytest]
testpaths = charcoal_cli/test_suite
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs = .git __pycache__ *.egg-info charcoal_cli/actions charcoal_cli/commands charcoal_cli/lib
